# Generated by Django 5.2.6 on 2025-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
