# Generated by Django 5.2.6 on 2025-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0003_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
