# Generated by Django 5.2.6 on 2025-11-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0006_productitem_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='rent_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('resell', 'Resell')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
