# Generated by Django 5.2.6 on 2025-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0007_productitem_rent_per_day_alter_productitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='type',
        ),
        migrations.AddField(
            model_name='productitem',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='is_resell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='resell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
