# Generated by Django 5.2.6 on 2025-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0008_remove_productitem_price_remove_productitem_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='resell_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_rent',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_resell',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='is_sell',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='productitem',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitem',
            name='type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('resell', 'Resell')], default='rent', max_length=10),
            preserve_default=False,
        ),
    ]
