# Generated by Django 5.2.6 on 2025-11-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0009_rename_resell_price_productitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainproject.userregistration'),
        ),
    ]
