# Generated by Django 5.2.6 on 2025-11-16 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0010_alter_productitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_bookings', to='Mainproject.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainproject.userregistration')),
            ],
            options={
                'verbose_name': 'Product Booking',
                'verbose_name_plural': 'Product Bookings',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'booking_date')},
            },
        ),
    ]
