# Generated by Django 5.2.6 on 2025-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0011_productbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbooking',
            old_name='booking_date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='productbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='start_date',
            field=models.DateField(default='2025-11-16'),
            preserve_default=False,
        ),
    ]
