# Generated by Django 5.2.4 on 2025-09-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
    ]
